# Define the C compiler to use
CC = gcc

# Define any compile-time flags
CFLAGS = -Wall -g

# Define any libraries to link
LIBS = -lcs50

# Phony targets
.PHONY: inheritance

inheritance:
	$(CC) $(CFLAGS) -o $@ inheritance.c $(LIBS)
